### ISSUE TITLE
Fat-utils repository not found

### ISSUE THREAD

**Issue by Bobur-kobilov** [Sphereon-Opensource/factom-daml-integration#6]
Hi, I cannot find fat-utils repository. 
Thank you

**Comment by LDMGN** [comment]
Thanks for reporting the issue @Bobur-kobilov . Looks like the referenced repository was misplaced. I've created a new repository at https://github.com/Sphereon-Opensource/fat-utils and updated the link in the README.

**Comment by LDMGN** [comment]
Closing this issue as the reference now works. Let us know if there are any further questions or issues.
